# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3c67064a8dbd0c995bed9c53d9ba792dd5fcb6d0c619381554a58674b6eca46f5d598f6228e028efce2dcdc5f7c3f2ffe3e8980af9fb7e39a2a64755be00f3cf

test:
  secret_key_base: 0a548293af57fdda1f6c19194d67624e245444b302c0f9c34ad53223fd77045b5c40664043ce3ec3db42b13bc44ac6270a97bea9babf638cb244c424b991c6bf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
